steps:
  - label: ":buildkite: Run regular pipeline"
    trigger: "rss-fetcher"
    build:
      branch: "${BUILDKITE_BRANCH}"
      message: "Pre-publish"
  - wait: ~
  - label: ":docker: Push Image"
    command: "docker push benji7425/discord-rss-fetcher:latest"
  - label: ":github: Create Release"
    command: ".buildkite/release-creator/create-github-release.sh $BUILDKITE_BRANCH benji7425 discord-rss-fetcher"
    plugins:
      - docker#v3.3.0:
          image: benji7425/alpine-bash-curl
          environment: ["GITHUB_TOKEN"]
    soft_fail: true